<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Dariusz Larsen">    
    <title>Employee Application</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"/>
    <link rel="stylesheet" href="/css/style.css" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="/js/script.js"></script>
</head>
<body class="bg-warning">
    <div class="row">  
        <header class="container text-center bg-primary text-white pb-4 p-3 fs-1">
            List of Employees
        </header>
    </div>
    <div class="row p-4">
        <div>
            <button type="button" class="btn btn-success" oninput="checkInputs()"><a style="text-decoration: none; color: white;" href="/employee/new">Add new employee</a></button>
        </div>
        <div class="row p-5">
        <form id="item_list" method="post">
        <div class="row">
        <div class="col-md-4">
        <input id="inputFilter" type="text" class="form-control" placeholder="Search for text in any colum...">
        </div>
        </div>
        <table class="table table-striped table-hover m-3 p-2">
            <tr class="table-row">
                <th>First Name</th>
                <th>Last Name</th>
                <th>Address</th>
                <th>PESEL</th>
                <th>Birth date</th>
                <th>Sex</th>
                <th>
                <button type="submit" id="deleteButton" class="btn btn-danger" id="delete_btn" disabled>delete</button>
                </th>    
            </tr>
<?php foreach ($employees as $employee)  { $i = 0 ?>
            <tbody id="table_report">
            <tr>
                <td><?=$employee->getFirstName() ?></td>
                <td><?=$employee->getLastName() ?></td>
                <td><?=$employee->getAddress() ?></td>
                <td><?=$employee->getPesel() ?></td>
                <td><?=$employee->getBirthDate() ?></td>
                <td><?=$employee->getSex() ?></td>
                <td>
                <input type="radio" class="ms-4" name="selection" id="<?= $employee->getId() ?>" value="<?= $employee->getId() ?>" onchange="checkRadioSelection()">
                </td>
                <td>
                <button type="submit" class="btn btn-secondary"><a href="<?=$router->pathFor('employee-modify', ['id' => $employee->getId()])?>">Modify</a></button>

                </td>
            </tr>

<?php }; ?>
                </tbody>
        </table>
</form>
        </div>
    </div>
    <div id="footer_add_employee" class="row">  
        <footer class="container text-center bg-primary text-white pt-4 p-3 fs-3">
            <p>for IWQ</p>
        </footer>
    </div>
</body>
</html>