<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Dariusz Larsen">    
    <title>Employee Application</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"/>
    <link rel="stylesheet" href="/css/style.css" type="text/css"/>
</head>
<body class="bg-warning">
    <div class="row">  
        <header class="container text-center bg-primary text-white pb-4 p-3 fs-1">
            List of Employees
        </header>
    </div>
    <div class="row p-4">
        <div>
            <button type="button" class="btn btn-success"><a style="text-decoration: none; color: white;" href="/employee/new">Add new employee</a></button>
        </div>
        <div class="row p-5">
        <form id="item_list" method="POST">
        <table class="table table-striped table-hover m-3 p-5">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Address</th>
                <th>PESEL</th>
                <th>Birth date</th>
                <th>Sex</th>
                <th>
                <button type="submit" class="btn btn-danger">delete</button>
                <button type="submit" class="btn btn-light">modify</button>
                <button type="submit" class="btn btn-info">views</button>
                </th>    
            </tr>
<?php foreach ($employees as $employee)  { $i = 0 ?>

            <tr>
                <td><?=$employee->getFirstName() ?></td>
                <td><?=$employee->getLastName() ?></td>
                <td><?=$employee->getAddress() ?></td>
                <td><?=$employee->getPesel() ?></td>
                <td><?=$employee->getBirthDate() ?></td>
                <td><?=$employee->getSex() ?></td>
                <td>

                <input type="radio" name="selection" id="<?= $employee->getId() ?>" value="<?= $employee->getId() ?>">

                </td>
                <td>
                <a href="<?=$router->pathFor('employee-detail', ['id' => $employee->getId()])?>">view details</a>
                </td>
                <td>
                <button type="submit" class="btn btn-danger">delete</button>
                </td>
            </tr>

<?php }; ?>
        </table>
</form>
        </div>
    </div>
    <div class="row">  
        <footer class="container text-center bg-primary text-white pt-4 p-3 fs-3">
            <p>for IWQ</p>
        </footer>
    </div>
</body>
</html>