<html>
<head>
    <title>Employee Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Employee</h1>

<form class="pure-form" method="post" action="/employee/new">
    <label for="first_name">First Name</label>
    <input name="first_name" id="first_name" type="text" size="60" /><br />

    <label for="last_name">Last Name</label>
    <input name="last_name" id="last_name" type="text" size="60" /><br />

    <label for="address">Address</label>
    <textarea name="address" id="address" rows="6" cols="80"></textarea><br />

    <label for="pesel">PESEL</label>
    <input name="pesel" id="pesel" type="text" size="60" /><br />

    </select><br />

    <input type="submit" class="pure-button" value="Create" />
</form>
</body>
</html>


